# Generated by Django 3.2.6 on 2021-08-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configrequest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='configrequest',
            name='value',
        ),
        migrations.AddField(
            model_name='configrequest',
            name='data',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='configrequest',
            name='remote_addr',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='configrequest',
            name='user_agent',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
